# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

matrix:
  allow_failures:
    - nodejs_version: "8"
    - nonadmin: true
environment:
  matrix:
    # node.js
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "6"
      nonadmin: true
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"


install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - ver
  - node --version
  - npm --version
  - icacls . /grant:r "%USERDOMAIN%\%USERNAME%":(OI)(CI)(F) /inheritance:d # This _should_ give unprivilidged access
  - icacls test\fixtures
  - cmd: if "%nonadmin%"=="true" (psexec -accepteula -l -w %CD% \\localhost cmd /c md test\out-fixtures) else  (md test\out-fixtures)
  - icacls test\out-fixtures
  - cmd: if "%nonadmin%"=="true" (psexec -accepteula -l -w %CD% \\localhost cmd /c npm test) else  (npm test)

build: off

# build version format
version: "{build}"
